update dockerfile

diff --git a/projects/golang/ticket-manager/_docker/Dockerfile b/projects/golang/ticket-manager/_docker/Dockerfile
--- a/projects/golang/ticket-manager/_docker/Dockerfile
+++ b/projects/golang/ticket-manager/_docker/Dockerfile
@@ -23,6 +23,10 @@ COPY --from=0 /opt/app/config/Config.yaml  /root/config/Config.yaml
 COPY --from=0 /opt/app/web /root/web/
 
 RUN ls -all
-RUN chmod 777 ticket-manager
+RUN chmod 777 ticket-
+
+# health check
+# HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
+#   CMD curl -fs http://localhost:8080 || exit 1
 
 CMD ["./ticket-backend"]
diff --git a/projects/java/ticket-frontend/_docker/Dockerfile b/projects/java/ticket-frontend/_docker/Dockerfile
--- a/projects/java/ticket-frontend/_docker/Dockerfile
+++ b/projects/java/ticket-frontend/_docker/Dockerfile
@@ -22,4 +22,8 @@ COPY --from=0 /opt/app/ticket-frontend.jar /root
 RUN ls -all
 RUN chmod 777 ticket-frontend.jar
 
+# health check
+# HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
+#   CMD curl -fs http://localhost:8090 || exit 1
+
 CMD ["java -jar /root/ticket-frontend.jar"]
